version: '3.1'

services:

  db:
    image: postgres:14-alpine
    container_name: postgres14
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: secret

  adminer:
    image: adminer
    container_name: postgres_adminer
    restart: always
    ports:
      - "8080:8080"